name = "CryptWalker"
defaultTargets = ["CryptWalker"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0-rc1"

[[require]]
name = "Bench"
git = "https://github.com/david415/bench"
rev = "main"

[[lean_lib]]
name = "CryptWalker"

[[lean_exe]]
name = "CryptWalker.Data.test"

[[lean_exe]]
name = "CryptWalker.NIKE.test"

[[lean_exe]]
name = "CryptWalker.KEM.test"

[[lean_exe]]
name = "CryptWalker.NIKE.benchmark"
[[lean_exe]]
name = "CryptWalker.KEM.vectors"

[[lean_exe]]
name = "CryptWalker.Hash.test"

[[lean_exe]]
name = "CryptWalker.Hash.hkdf_test"

[[lean_exe]]
name = "CryptWalker.Cipher.test"

[[lean_exe]]
name = "CryptWalker.Sign.test"

[[lean_exe]]
name = "CryptWalker.Sign.blinded_test"
