/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json
import CryptWalker.MultiRecipientHybrid.Schemes
import CryptWalker.Util.newhex

/-! # Multi-recipient hybrid vectors, for cross-checking against hpqc

As `KEM/gen_mlkem768_hedged_vectors.lean`: builds vectors with the Lean side's own computation (real
IO randomness, recorded as drawn), in the schema `multirecipient_hybrid_test.lean` checks, so hpqc's
`kem/mrhybrid` tests can decapsulate them with `"MLKEM768-X25519"`. Uses
`hybridMLKEM768X25519Blake2b`. Each recipient's decapsulation, and the reply, is checked here before
the vector is written. -/

open Lean
open CryptWalker.KEM (kemX25519Blake2b kemMLKEM768X25519Blake2b)
open CryptWalker.MultiRecipientHybrid.MultiRecipientHybrid (Ciphertext)
open CryptWalker.MultiRecipientHybrid.Schemes (hybridMLKEM768X25519Blake2b)
open CryptWalker.Util.newhex
open CryptWalker.Util.Bytes (ofVector toVecN)

def H := hybridMLKEM768X25519Blake2b
def K := kemMLKEM768X25519Blake2b

def hexOfB (b : ByteArray) : String := byteArrayToHex b

def randomVector (n : Nat) : IO (Vector UInt8 n) := do
  let bs ← IO.getRandomBytes (USize.ofNat n)
  pure (Vector.ofFn fun i : Fin n => bs[i.val]!)

structure Recipient where
  x : Vector UInt8 32
  d : Vector UInt8 32
  z : Vector UInt8 32
  sk : K.PrivateKey

def newRecipient : IO Recipient := do
  let x ← randomVector 32
  let d ← randomVector 32
  let z ← randomVector 32
  let some xsk := kemX25519Blake2b.decodePrivateKey x
    | throw (IO.userError "x25519 private key decode failed")
  pure { x, d, z, sk := (show K.PrivateKey from (xsk, ((d, z), PUnit.unit))) }

def buildVec (name : String) (n : Nat) (payload : ByteArray) : IO Json := do
  let rs ← (List.range n).mapM fun _ => newRecipient
  let seed ← randomVector 32
  let keys : List H.PublicKey := rs.map fun r => K.derivePublicKey r.sk
  match H.encapsulate keys payload (H.stateFromSeed seed) with
  | .error _ _ => throw (IO.userError s!"{name}: encapsulate failed")
  | .ok (derivedKeys, ct) s =>
    let mut recips := #[]
    for i in [0:n] do
      let some r := rs[i]? | throw (IO.userError "recipient index")
      let some k := derivedKeys[i]? | throw (IO.userError "derived key index")
      let some kc := ct.kemCiphertexts[i]? | throw (IO.userError "kem ciphertext index")
      let some dek := ct.deks[i]? | throw (IO.userError "dek index")
      match H.decapsulate (show H.PrivateKey from r.sk) (ct.forRecipient i) with
      | .ok (k', pt) =>
        if hexOfB k' ≠ hexOfB k ∨ hexOfB pt ≠ hexOfB payload then
          throw (IO.userError s!"{name}: recipient {i} decapsulation mismatch")
      | .error _ => throw (IO.userError s!"{name}: recipient {i} decapsulation failed")
      recips := recips.push (Json.mkObj [
        ("x25519_private_key_hex", Json.str (hexOfB (ofVector r.x))),
        ("mlkem_d_hex", Json.str (hexOfB (ofVector r.d))),
        ("mlkem_z_hex", Json.str (hexOfB (ofVector r.z))),
        ("derived_key_hex", Json.str (hexOfB k)),
        ("kem_ciphertext_hex", Json.str (hexOfB (ofVector (K.encodeCiphertext kc)))),
        ("dek_hex", Json.str (hexOfB dek))])
    let some k0 := derivedKeys.head? | throw (IO.userError "no recipients")
    let reply := s!"reply to {name}".toUTF8
    match H.envelopeReply k0 reply s with
    | .error _ _ => throw (IO.userError s!"{name}: reply failed")
    | .ok env _ =>
      match H.decryptEnvelope k0 env with
      | .ok pt => if hexOfB pt ≠ hexOfB reply then throw (IO.userError s!"{name}: reply mismatch")
      | .error _ => throw (IO.userError s!"{name}: reply decrypt failed")
      pure (Json.mkObj [
        ("name", Json.str name),
        ("payload_hex", Json.str (hexOfB payload)),
        ("recipients", Json.arr recips),
        ("envelope_hex", Json.str (hexOfB ct.envelope)),
        ("reply_plaintext_hex", Json.str (hexOfB reply)),
        ("reply_envelope_hex", Json.str (hexOfB env))])

def main : IO UInt32 := do
  let payload3 := ByteArray.mk ((List.replicate 8 "three recipients ".toUTF8.toList).flatten.toArray)
  let vecs := #[
    ← buildVec "lean_case_1" 1 ByteArray.empty,
    ← buildVec "lean_case_2" 2 "one payload, two recipients".toUTF8,
    ← buildVec "lean_case_3" 3 payload3]
  let out := Json.mkObj [
    ("format_version", Json.num 1),
    ("generator", Json.str "CryptWalker/MultiRecipientHybrid/gen_multirecipient_hybrid_vectors.lean"),
    ("primitive", Json.str "multirecipient_hybrid_mlkem768_x25519"),
    ("description", Json.str "Multi-recipient hybrid encryption over X25519 (blake2b-xof adapter PRF) combined with ML-KEM-768, AES-256-GCM-SIV and BLAKE2b-256, generated by the Lean port's hybridMLKEM768X25519Blake2b for cross-checking against hpqc's kem/mrhybrid over MLKEM768-X25519."),
    ("vectors", Json.arr vecs)]
  let outPath := "testdata/lean_multirecipient_hybrid_vectors.json"
  IO.FS.writeFile outPath out.pretty
  IO.println s!"wrote {outPath}"
  pure 0
