/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json

import CryptWalker.GroupChat.AckCodec
import CryptWalker.Util.newhex

/-! # `Acks` field vectors

Reads `testdata/acks_vectors.json`, from katzenqt's `tests/data/acks_vectors.json`: fields
generated by the Go reference codec and reproduced byte for byte by the Python and Rust codecs.
Each case must encode to exactly the field given, and the field must decode back, under both the
spec's parser and the strict one. -/

open Lean
open CryptWalker.GroupChat.AckCodec
open CryptWalker.Util.newhex

/-- The contents of a CBOR byte string. -/
def cborBytes (b : List ℕ) : Option (List ℕ) :=
  match b with
  | h :: rest =>
    if 0x40 ≤ h ∧ h < 0x58 then some rest
    else if h = 0x58 then some (rest.drop 1)
    else if h = 0x59 then some (rest.drop 2)
    else if h = 0x5a then some (rest.drop 4)
    else none
  | [] => none

def hexNats (s : String) : Except String (List ℕ) :=
  match hexStringToByteArray s with
  | some b => pure (b.toList.map (·.toNat))
  | none => throw s!"not valid hex: {s}"

def runCase (j : Json) : Except String String := do
  let name ← (← j.getObjVal? "name").getStr?
  let v ← (← j.getObjVal? "value_size").getNat?
  let raw ← (← j.getObjVal? "acks").getArr?
  let mut acks : List (ℕ × List ℕ) := []
  for pair in raw do
    let p ← pair.getArr?
    let i ← (p[0]!).getNat?
    let value ← hexNats (← (p[1]!).getStr?)
    acks := acks ++ [(i, value)]
  let sorted := acks.mergeSort (fun a b => a.1 ≤ b.1)
  let some field := cborBytes (← hexNats (← (← j.getObjVal? "cbor").getStr?))
    | throw s!"{name}: not a CBOR byte string"
  if encode sorted != field then throw s!"{name}: encodes differently"
  if decode false v field != some sorted then throw s!"{name}: the spec's parser misreads it"
  if decode true v field != some sorted then throw s!"{name}: the strict parser misreads it"
  pure s!"{name} ({sorted.length} acknowledged, {field.length} bytes)"

def main : IO UInt32 := do
  let text ← IO.FS.readFile "testdata/acks_vectors.json"
  let cases ← IO.ofExcept do
    let j ← Json.parse text
    (← j.getObjVal? "cases").getArr?
  let mut ok := true
  for c in cases do
    match runCase c with
    | .ok msg => IO.println s!"  ok    {msg}"
    | .error e => ok := false; IO.println s!"  FAIL  {e}"
  if ok then
    IO.println s!"all {cases.size} Acks vectors passed"
    pure 0
  else
    IO.eprintln "some Acks vectors FAILED"
    pure 1
