/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json
import CryptWalker.Hash.Sha512
import CryptWalker.Sphinx.Crypto.HMAC
import CryptWalker.Sphinx.Crypto.Stream
import CryptWalker.Sphinx.Crypto.KDF
import CryptWalker.Sphinx.Crypto.ChaCha20
import CryptWalker.Util.newhex

/-!
# Sphinx primitive-layer known-answer tests: Hash, MAC, Stream, KDF, ChaCha20

Checks the "glue" primitives Sphinx's `internal/crypto` composes (everything except the SPRP,
which gets its own `aez_test` given its size) against vectors generated by
`katzenpost/core/sphinx/testvectors/cmd/generate` and vendored here, following the same
convention as `KEM/vectors.lean`. Each `testdata/sphinx_*.json.sha256` records which copy this
is. ChaCha20 (`hpqc/rand.NewDeterministicRandReader`'s cipher) isn't part of `internal/crypto`
itself, but is needed downstream by `NikeSphinx`'s per-hop `BlindingFactor` derivation, so it's
checked here alongside its siblings.
-/

open Lean
open CryptWalker.Util.newhex
open CryptWalker.Hash.Sha512 (sha512_256)
open CryptWalker.Sphinx.Crypto.ChaCha20 (keystream32)
open CryptWalker.Sphinx.Crypto.HMAC (hmacSha256)
open CryptWalker.Sphinx.Crypto.Stream (keystream)
open CryptWalker.Sphinx.Crypto.KDF (sphinxKDF PacketKeys)

def field (j : Json) (k : String) : Except String ByteArray := do
  let s ← (← j.getObjVal? k).getStr?
  match hexStringToByteArray s with
  | some b => pure b
  | none   => throw s!"field {k}: not valid hex: {s}"

def hexOfV {n} (v : Vector UInt8 n) : String := byteArrayToHex ⟨v.toArray⟩
def hexOfB (b : ByteArray) : String := byteArrayToHex b

/-- Reinterpret a `ByteArray` as a fixed-width vector, or `none` if the length doesn't match. -/
def toVecN (n : Nat) (b : ByteArray) : Option (Vector UInt8 n) :=
  if h : b.data.size = n then some ⟨b.data, h⟩ else none

def loadPrimitive (path prim : String) : IO (Except String (Array Json)) := do
  let raw ← IO.FS.readFile path
  match Json.parse raw with
  | .error e => pure (.error s!"failed to parse {path}: {e}")
  | .ok j =>
    match j.getObjVal? "primitive" >>= Json.getStr? with
    | .error e => pure (.error e)
    | .ok p =>
      if p ≠ prim then pure (.error s!"unexpected primitive in {path}: {p}")
      else match j.getObjVal? "vectors" >>= Json.getArr? with
        | .error e => pure (.error e)
        | .ok arr  => pure (.ok arr)

/-! ## Hash: SHA-512/256 -/

def runHash : IO Bool := do
  match ← loadPrimitive "testdata/sphinx_hash_sha512_256.json" "sha512_256" with
  | .error e => do IO.eprintln e; pure false
  | .ok arr => do
    IO.println s!"SHA-512/256 (replay-tag hash, {arr.size} vectors)"
    let mut ok := true
    for j in arr do
      match (do
        let name ← (← j.getObjVal? "name").getStr?
        let input ← field j "input_hex"
        let output ← field j "output_hex"
        pure (name, input, output) : Except String _) with
      | .error e => do IO.eprintln e; ok := false
      | .ok (name, input, want) =>
        let got := hexOfV (sha512_256 input)
        if got == hexOfB want then
          IO.println s!"  ok    {name}"
        else
          ok := false
          IO.println s!"  FAIL  {name}"
          IO.println s!"          want {hexOfB want}"
          IO.println s!"          got  {got}"
    pure ok

/-! ## MAC: HMAC-SHA256 -/

def runMAC : IO Bool := do
  match ← loadPrimitive "testdata/sphinx_mac_hmac_sha256.json" "hmac_sha256" with
  | .error e => do IO.eprintln e; pure false
  | .ok arr => do
    IO.println s!"HMAC-SHA256 (header MAC, {arr.size} vectors)"
    let mut ok := true
    for j in arr do
      match (do
        let name ← (← j.getObjVal? "name").getStr?
        let key ← field j "key_hex"
        let msg ← field j "msg_hex"
        let mac ← field j "mac_hex"
        pure (name, key, msg, mac) : Except String _) with
      | .error e => do IO.eprintln e; ok := false
      | .ok (name, key, msg, want) =>
        let got := hexOfV (hmacSha256 key msg)
        if got == hexOfB want then
          IO.println s!"  ok    {name}"
        else
          ok := false
          IO.println s!"  FAIL  {name}"
          IO.println s!"          want {hexOfB want}"
          IO.println s!"          got  {got}"
    pure ok

/-! ## Stream: AES-256-CTR -/

def runStream : IO Bool := do
  match ← loadPrimitive "testdata/sphinx_stream_aes256ctr.json" "stream_aes256ctr" with
  | .error e => do IO.eprintln e; pure false
  | .ok arr => do
    IO.println s!"AES-256-CTR (header/routing-info keystream, {arr.size} vectors)"
    let mut ok := true
    for j in arr do
      match (do
        let name ← (← j.getObjVal? "name").getStr?
        let key ← field j "key_hex"
        let iv ← field j "iv_hex"
        let ks ← field j "keystream_hex"
        pure (name, key, iv, ks) : Except String _) with
      | .error e => do IO.eprintln e; ok := false
      | .ok (name, keyB, ivB, want) =>
        match toVecN 32 keyB, toVecN 16 ivB with
        | some key, some iv =>
          let got := hexOfB (keystream key iv want.size)
          if got == hexOfB want then
            IO.println s!"  ok    {name}"
          else
            ok := false
            IO.println s!"  FAIL  {name}"
            IO.println s!"          want {hexOfB want}"
            IO.println s!"          got  {got}"
        | _, _ => do IO.eprintln s!"{name}: key or iv wrong length"; ok := false
    pure ok

/-! ## KDF: HKDF-SHA256 Expand-only PacketKeys derivation -/

def runKDF : IO Bool := do
  match ← loadPrimitive "testdata/sphinx_kdf.json" "kdf_sphinx" with
  | .error e => do IO.eprintln e; pure false
  | .ok arr => do
    IO.println s!"Sphinx KDF (PacketKeys derivation, {arr.size} vectors)"
    let mut ok := true
    for j in arr do
      match (do
        let name ← (← j.getObjVal? "name").getStr?
        let ikm ← field j "ikm_hex"
        let mac ← field j "header_mac_hex"
        let henc ← field j "header_encryption_hex"
        let hiv ← field j "header_encryption_iv_hex"
        let penc ← field j "payload_encryption_hex"
        let seed ← field j "blinding_factor_seed_hex"
        pure (name, ikm, mac, henc, hiv, penc, seed) : Except String _) with
      | .error e => do IO.eprintln e; ok := false
      | .ok (name, ikm, wantMac, wantHenc, wantHiv, wantPenc, wantSeed) =>
        let got : PacketKeys := sphinxKDF ikm
        let checks := [
          ("header_mac", hexOfV got.headerMAC, hexOfB wantMac),
          ("header_encryption", hexOfV got.headerEncryption, hexOfB wantHenc),
          ("header_encryption_iv", hexOfV got.headerEncryptionIV, hexOfB wantHiv),
          ("payload_encryption", hexOfV got.payloadEncryption, hexOfB wantPenc),
          ("blinding_factor_seed", hexOfV got.blindingFactorSeed, hexOfB wantSeed)]
        let allOk := checks.all fun (_, got, want) => got == want
        if allOk then
          IO.println s!"  ok    {name}"
        else
          ok := false
          IO.println s!"  FAIL  {name}"
          for (label, got, want) in checks do
            if got ≠ want then
              IO.println s!"          {label}: want {want} got {got}"
    pure ok

/-! ## ChaCha20 (`hpqc/rand.NewDeterministicRandReader`) -/

def runChaCha20 : IO Bool := do
  match ← loadPrimitive "testdata/sphinx_chacha20_deterministic_rand.json" "chacha20_deterministic_rand" with
  | .error e => do IO.eprintln e; pure false
  | .ok arr => do
    IO.println s!"ChaCha20 deterministic-RNG keystream ({arr.size} vectors)"
    let mut ok := true
    for j in arr do
      match (do
        let name ← (← j.getObjVal? "name").getStr?
        let key ← field j "key_hex"
        let ks ← field j "keystream_hex"
        pure (name, key, ks) : Except String _) with
      | .error e => do IO.eprintln e; ok := false
      | .ok (name, key, want) =>
        let got := (⟨keystream32 key.data⟩ : ByteArray)
        if hexOfB got == hexOfB want then
          IO.println s!"  ok    {name}"
        else
          ok := false
          IO.println s!"  FAIL  {name}"
          IO.println s!"          want {hexOfB want}"
          IO.println s!"          got  {hexOfB got}"
    pure ok

def main : IO UInt32 := do
  let okHash ← runHash
  let okMAC ← runMAC
  let okStream ← runStream
  let okKDF ← runKDF
  let okChaCha20 ← runChaCha20
  IO.println ""
  if okHash && okMAC && okStream && okKDF && okChaCha20 then
    IO.println "all Sphinx primitive-layer vectors passed"
    pure 0
  else
    IO.eprintln "Sphinx primitive-layer vectors FAILED"
    pure 1
