/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json
import CryptWalker.KEM.Schemes
import CryptWalker.Util.newhex

/-! # X25519 + ML-KEM-768 hybrid combiner vectors, for cross-checking against hpqc

As `Sphinx.gen_kem_vectors`: builds vectors with the Lean side's own computation (real IO
randomness, not a fixed seed -- whatever concrete values are drawn get recorded), in the same
schema `mlkem768_x25519_combiner_test.lean` checks, so hpqc's `kem/combiner` test suite can
reconstruct each component from the recorded raw inputs and confirm it agrees on the combined
ciphertext and shared secret.

Uses `kemX25519Blake2b`, the deployed `blake2b-xof` adapter PRF. -/

open Lean
open CryptWalker.Util.newhex
open CryptWalker.KEM
open MLKEM
open CryptWalker.KEM.MLKEM768 (keygen768 encaps768 params encoding tBytes uBytes vBytes)
open CryptWalker.Util.Bytes (ofVector toVecN)

def hexOfB (b : ByteArray) : String := byteArrayToHex b

def encodeEKRaw (ek : EncapsulationKey params encoding) : ByteArray :=
  tBytes ek.tHatEncoded ++ ofVector ek.rho

def encodeCTRaw (c : Ciphertext params encoding) : ByteArray :=
  uBytes c.uEncoded ++ vBytes c.vEncoded

def randomVector (n : Nat) : IO (Vector UInt8 n) := do
  let bs ← IO.getRandomBytes (USize.ofNat n)
  pure (Vector.ofFn fun i : Fin n => bs[i.val]!)

def buildVec (name : String) : IO Json := do
  let staticPriv ← randomVector 32
  let ephPriv ← randomVector 32
  let some sk := kemX25519Blake2b.decodePrivateKey staticPriv
    | throw (IO.userError "x25519 static privkey decode failed")
  let pk := kemX25519Blake2b.derivePublicKey sk
  match kemX25519Blake2b.encap pk (kemX25519Blake2b.stateFromSeed ephPriv) with
  | .error _ _ => throw (IO.userError "x25519 encap failed")
  | .ok (ctX25519, ssX25519) _ =>
    let ctX25519Bytes := ofVector (kemX25519Blake2b.encodeCiphertext ctX25519)
    let ssX25519Bytes := ofVector (kemX25519Blake2b.encodePlaintext ssX25519)

    let d ← randomVector 32
    let z ← randomVector 32
    let m ← randomVector 32
    let (ek, _dk) := keygen768 d z
    let (ssMLKEM, ctMLKEM) := encaps768 ek m
    let ctMLKEMBytes := encodeCTRaw ctMLKEM
    let ssMLKEMBytes := ofVector ssMLKEM

    let combinedCt := ctX25519Bytes ++ ctMLKEMBytes
    let combinedSs := Combiner.splitPRF blake2b256CombinerPRF
      (ssX25519Bytes, ctX25519Bytes) [(ssMLKEMBytes, ctMLKEMBytes)]

    pure (Json.mkObj [
      ("name", Json.str name),
      ("prf", Json.str "blake2b-xof"),
      ("x25519_static_private_key_hex", Json.str (hexOfB (ofVector staticPriv))),
      ("x25519_static_public_key_hex", Json.str (hexOfB (ofVector (kemX25519Blake2b.encodePublicKey pk)))),
      ("x25519_ephemeral_private_key_hex", Json.str (hexOfB (ofVector ephPriv))),
      ("x25519_ciphertext_hex", Json.str (hexOfB ctX25519Bytes)),
      ("x25519_shared_secret_hex", Json.str (hexOfB ssX25519Bytes)),
      ("mlkem_d_hex", Json.str (hexOfB (ofVector d))),
      ("mlkem_z_hex", Json.str (hexOfB (ofVector z))),
      ("mlkem_m_hex", Json.str (hexOfB (ofVector m))),
      ("mlkem_encapsulation_key_hex", Json.str (hexOfB (encodeEKRaw ek))),
      ("mlkem_ciphertext_hex", Json.str (hexOfB ctMLKEMBytes)),
      ("mlkem_shared_secret_hex", Json.str (hexOfB ssMLKEMBytes)),
      ("combined_ciphertext_hex", Json.str (hexOfB combinedCt)),
      ("combined_shared_secret_hex", Json.str (hexOfB (ofVector combinedSs)))])

def main : IO UInt32 := do
  let names := ["lean_case_1", "lean_case_2", "lean_case_3"]
  let vecs ← names.toArray.mapM buildVec
  let out := Json.mkObj [
    ("format_version", Json.num 1),
    ("generator", Json.str "CryptWalker/KEM/gen_mlkem768_x25519_combiner_vectors.lean"),
    ("primitive", Json.str "mlkem768_x25519_combiner"),
    ("description", Json.str "X25519 (blake2b-xof adapter PRF) combined with ML-KEM-768 via the generic split-PRF combiner, generated by the Lean port for cross-checking against hpqc."),
    ("vectors", Json.arr vecs)]
  let outPath := "testdata/lean_mlkem768_x25519_combiner_vectors.json"
  IO.FS.writeFile outPath out.pretty
  IO.println s!"wrote {outPath}"
  pure 0
