/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json
import CryptWalker.KEM.MLKEMHedged.MLKEMHedged768
import CryptWalker.Util.newhex

/-! # Hedged ML-KEM-768 vectors, for cross-checking against hpqc

As `gen_mlkem768_x25519_combiner_vectors.lean`: builds vectors with the Lean side's own computation
(real IO randomness, recorded as drawn), in the schema `mlkem768_hedged_test.lean` checks, so hpqc's
`kem/mlkem768` tests can check its `"MLKEMHedged768"` against them. Each vector is decapsulated
here before it is written. -/

open Lean
open MLKEM
open CryptWalker.KEM.MLKEM768 (hashH uBytes vBytes)
open CryptWalker.KEM.MLKEMHedged
open CryptWalker.Util.newhex
open CryptWalker.Util.Bytes (ofVector toVecN)

def hexOfB (b : ByteArray) : String := byteArrayToHex b

def randomVector (n : Nat) : IO (Vector UInt8 n) := do
  let bs ← IO.getRandomBytes (USize.ofNat n)
  pure (Vector.ofFn fun i : Fin n => bs[i.val]!)

def buildVec (name : String) : IO Json := do
  let K := kemMLKEMHedged768Seed
  let d ← randomVector 32
  let z ← randomVector 32
  let m ← randomVector 32
  let sk := (d, z)
  let pk := K.derivePublicKey sk
  let (ss, ct) := encaps768Hedged (show CryptWalker.KEM.MLKEM768.PublicKey from pk).1 m
  let ctBytes := uBytes ct.uEncoded ++ vBytes ct.vEncoded
  let some c := K.decodeCiphertext (toVecN _ ctBytes)
    | throw (IO.userError "ciphertext decode failed")
  match K.decap sk c K.stateI.default with
  | .ok k _ =>
    if hexOfB (ofVector (K.encodePlaintext k)) ≠ hexOfB (ofVector ss) then
      throw (IO.userError s!"{name}: decapsulation mismatch")
  | .error _ _ => throw (IO.userError s!"{name}: decapsulation failed")
  pure (Json.mkObj [
    ("name", Json.str name),
    ("d_hex", Json.str (hexOfB (ofVector d))),
    ("z_hex", Json.str (hexOfB (ofVector z))),
    ("m_hex", Json.str (hexOfB (ofVector m))),
    ("m_hash_hex", Json.str (hexOfB (ofVector (hashH (ofVector m))))),
    ("encapsulation_key_hex", Json.str (hexOfB (ofVector (K.encodePublicKey pk)))),
    ("ciphertext_hex", Json.str (hexOfB ctBytes)),
    ("shared_secret_hex", Json.str (hexOfB (ofVector ss)))])

def main : IO UInt32 := do
  let names := ["lean_case_1", "lean_case_2", "lean_case_3", "lean_case_4", "lean_case_5"]
  let vecs ← names.toArray.mapM buildVec
  let out := Json.mkObj [
    ("format_version", Json.num 1),
    ("generator", Json.str "CryptWalker/KEM/gen_mlkem768_hedged_vectors.lean"),
    ("primitive", Json.str "mlkem768_hedged"),
    ("description", Json.str "Hedged ML-KEM-768 (FIPS 203 ML-KEM-768 with round-3 Kyber's pre-hash of m restored, H = SHA3-256), generated by the Lean port's kemMLKEMHedged768Seed and encaps768Hedged for cross-checking against hpqc's MLKEMHedged768."),
    ("vectors", Json.arr vecs)]
  let outPath := "testdata/lean_mlkem768_hedged_vectors.json"
  IO.FS.writeFile outPath out.pretty
  IO.println s!"wrote {outPath}"
  pure 0
