/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json
import CryptWalker.KEM.Schemes
import CryptWalker.Util.newhex

/-! # X25519 + ML-KEM-768 hybrid combiner: cross-repo known-answer tests

Checks `kemMLKEM768X25519`'s two ingredients and the combiner glue against vectors generated by
`hpqc/testvectors/cmd/generate`'s `genKEMHybridCombiner` (`testdata/mlkem768_x25519_combiner.json`,
also checked by hpqc's own `kem/combiner` test suite). hpqc's registered `"MLKEM768-X25519"` scheme
defaults its X25519 half to the deployed BLAKE2b-XOF adapter PRF, which this project hasn't
ported (see `KEM/vectors.lean`'s module doc); these vectors instead fix the X25519 half to
`sha256-v1`, exactly `kemX25519`, so the whole hybrid is checkable here -- the same accepted scope
boundary `KEM/vectors.lean` already documents for the plain adapter.

Each vector gives every component's raw inputs and every intermediate output, so the check covers
X25519 keygen/encap/decap, ML-KEM-768 keygen/encap, and the combiner's ciphertext concatenation and
`splitPRF` (now real BLAKE2b-256, matching hpqc's deployed combiner) all at once. -/

open Lean
open CryptWalker.Util.newhex
open CryptWalker.KEM
open MLKEM
open CryptWalker.KEM.MLKEM768 (keygen768 encaps768 params encoding tBytes uBytes vBytes)
open CryptWalker.Util.Bytes (ofVector toVecN)

def field (j : Json) (k : String) : Except String ByteArray := do
  let s ← (← j.getObjVal? k).getStr?
  match hexStringToByteArray s with
  | some b => pure b
  | none   => throw s!"field {k}: not valid hex: {s}"

def hexOfB (b : ByteArray) : String := byteArrayToHex b

def encodeEKRaw (ek : EncapsulationKey params encoding) : ByteArray :=
  tBytes ek.tHatEncoded ++ ofVector ek.rho

def encodeCTRaw (c : Ciphertext params encoding) : ByteArray :=
  uBytes c.uEncoded ++ vBytes c.vEncoded

structure Vec where
  name             : String
  x25519StaticPriv : ByteArray
  x25519StaticPub  : ByteArray
  x25519EphPriv    : ByteArray
  x25519Ct         : ByteArray
  x25519Ss         : ByteArray
  mlkemD           : ByteArray
  mlkemZ           : ByteArray
  mlkemM           : ByteArray
  mlkemEk          : ByteArray
  mlkemCt          : ByteArray
  mlkemSs          : ByteArray
  combinedCt       : ByteArray
  combinedSs       : ByteArray

def parseVec (j : Json) : Except String Vec := do
  pure {
    name             := ← (← j.getObjVal? "name").getStr?
    x25519StaticPriv := ← field j "x25519_static_private_key_hex"
    x25519StaticPub  := ← field j "x25519_static_public_key_hex"
    x25519EphPriv    := ← field j "x25519_ephemeral_private_key_hex"
    x25519Ct         := ← field j "x25519_ciphertext_hex"
    x25519Ss         := ← field j "x25519_shared_secret_hex"
    mlkemD           := ← field j "mlkem_d_hex"
    mlkemZ           := ← field j "mlkem_z_hex"
    mlkemM           := ← field j "mlkem_m_hex"
    mlkemEk          := ← field j "mlkem_encapsulation_key_hex"
    mlkemCt          := ← field j "mlkem_ciphertext_hex"
    mlkemSs          := ← field j "mlkem_shared_secret_hex"
    combinedCt       := ← field j "combined_ciphertext_hex"
    combinedSs       := ← field j "combined_shared_secret_hex"
  }

def parseFile (s : String) : Except String (Array Vec) := do
  let j ← Json.parse s
  let prim ← (← j.getObjVal? "primitive").getStr?
  if prim ≠ "mlkem768_x25519_combiner" then throw s!"unexpected primitive: {prim}"
  let arr ← (← j.getObjVal? "vectors").getArr?
  arr.mapM parseVec

def check (label : String) (want got : ByteArray) : IO Bool := do
  if hexOfB want == hexOfB got then
    IO.println s!"    ok   {label}"
    pure true
  else
    IO.println s!"    FAIL {label}"
    IO.println s!"           want {hexOfB want}"
    IO.println s!"           got  {hexOfB got}"
    pure false

/-- The X25519 half: static keypair, ciphertext (= ephemeral pubkey), encap and decap shared
secrets. Returns the ciphertext/shared-secret bytes too, for the combined-vector checks below. -/
def runX25519 (v : Vec) : IO (Bool × ByteArray × ByteArray) := do
  match kemX25519.decodePrivateKey (toVecN 32 v.x25519StaticPriv) with
  | none => IO.println "    FAIL x25519 static privkey decode"; pure (false, ByteArray.empty, ByteArray.empty)
  | some sk =>
    let pk := kemX25519.derivePublicKey sk
    let mut ok := ← check "x25519 static pubkey" v.x25519StaticPub (ofVector (kemX25519.encodePublicKey pk))
    match kemX25519.encap pk (kemX25519.stateFromSeed (toVecN 32 v.x25519EphPriv)) with
    | .error _ _ => IO.println "    FAIL x25519 encap"; pure (false, ByteArray.empty, ByteArray.empty)
    | .ok (ct, ssEncap) _ =>
      let ctBytes := ofVector (kemX25519.encodeCiphertext ct)
      let ssBytes := ofVector (kemX25519.encodePlaintext ssEncap)
      ok := (← check "x25519 ciphertext" v.x25519Ct ctBytes) && ok
      ok := (← check "x25519 encap shared secret" v.x25519Ss ssBytes) && ok
      match kemX25519.decap sk ct (kemX25519.stateFromSeed (toVecN 32 v.x25519EphPriv)) with
      | .error _ _ => IO.println "    FAIL x25519 decap"; pure (false, ctBytes, ssBytes)
      | .ok ssDecap _ =>
        ok := (← check "x25519 decap shared secret" v.x25519Ss
          (ofVector (kemX25519.encodePlaintext ssDecap))) && ok
        pure (ok, ctBytes, ssBytes)

/-- The ML-KEM-768 half: keygen from `d`,`z`, encaps from `m`. Returns the ciphertext/shared-secret
bytes too. -/
def runMLKEM (v : Vec) : IO (Bool × ByteArray × ByteArray) := do
  let d := toVecN 32 v.mlkemD
  let z := toVecN 32 v.mlkemZ
  let m := toVecN 32 v.mlkemM
  let (ek, _dk) := keygen768 d z
  let mut ok ← check "mlkem768 encapsulation key" v.mlkemEk (encodeEKRaw ek)
  let (ss, ct) := encaps768 ek m
  let ctBytes := encodeCTRaw ct
  let ssBytes := ofVector ss
  ok := (← check "mlkem768 ciphertext" v.mlkemCt ctBytes) && ok
  ok := (← check "mlkem768 shared secret" v.mlkemSs ssBytes) && ok
  pure (ok, ctBytes, ssBytes)

def runVec (v : Vec) : IO Bool := do
  IO.println s!"  {v.name}"
  let (okX25519, ctX25519, ssX25519) ← runX25519 v
  let (okMLKEM, ctMLKEM, ssMLKEM) ← runMLKEM v
  let mut ok := okX25519 && okMLKEM
  ok := (← check "combined ciphertext" v.combinedCt (ctX25519 ++ ctMLKEM)) && ok
  let ssCombined := Combiner.splitPRF blake2b256CombinerPRF (ssX25519, ctX25519) [(ssMLKEM, ctMLKEM)]
  ok := (← check "combined shared secret" v.combinedSs (ofVector ssCombined)) && ok
  pure ok

def main : IO UInt32 := do
  let path := "testdata/mlkem768_x25519_combiner.json"
  let raw ← IO.FS.readFile path
  match parseFile raw with
  | .error e => IO.eprintln s!"failed to parse {path}: {e}"; pure 1
  | .ok vs =>
    IO.println s!"X25519 + ML-KEM-768 hybrid combiner vectors ({vs.size} from hpqc)"
    let mut ok := true
    for v in vs do
      ok := (← runVec v) && ok
    IO.println ""
    if ok then
      IO.println "all checks passed"
      pure 0
    else
      IO.eprintln "FAILED"
      pure 1
