/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json
import CryptWalker.KEM.Schemes
import CryptWalker.Util.newhex

/-!
# Cross-implementation test vectors for the NIKE-to-KEM adapter

Checks this Lean adapter against the canonical vectors generated by
`hpqc/testvectors/cmd/generate`, the same file the Go port checks in
`hpqc/kem/adapter/adapter_vectors_test.go`. It is vendored under `testdata/`
rather than symlinked because hpqc is a separate repository;
`testdata/adapter_test_vectors.json.sha256` records which copy this is.

Four checks per vector:

* the static public key derives from the static private key,
* the ciphertext is the encoded ephemeral public key,
* decapsulation reproduces the recorded shared secret, and
* the same shared secret is what encapsulation would produce from the recorded
  ephemeral — which is the check that pins the key ordering.

The PRF comes from each vector's `prf` field rather than being assumed. Vectors
naming a PRF this implementation lacks (`blake2b-xof`, the deployed one) are
reported as skipped. At least one vector must actually run, so a truncated file
cannot masquerade as a pass.
-/

open Lean
open CryptWalker.Util.newhex
open CryptWalker.KEM
open CryptWalker.KEM.KEM
open CryptWalker.KEM.Adapter
open CryptWalker.NIKE

/-- The PRFs this implementation can compute. `blake2b-xof` is absent until
CryptWalker has BLAKE2b/BLAKE2Xb. -/
def prfByName : String → Option Adapter.PRF
  | "sha256-v1" => some sha256v1PRF
  | _           => none

structure Vec where
  name       : String
  prf        : String
  staticPriv : ByteArray
  staticPub  : ByteArray
  ephPriv    : ByteArray
  ct         : ByteArray
  ss         : ByteArray

def field (j : Json) (k : String) : Except String ByteArray := do
  let s ← (← j.getObjVal? k).getStr?
  match hexStringToByteArray s with
  | some b => pure b
  | none   => throw s!"field {k}: not valid hex: {s}"

def parseVec (j : Json) : Except String Vec := do
  pure {
    name       := ← (← j.getObjVal? "name").getStr?
    prf        := ← (← j.getObjVal? "prf").getStr?
    staticPriv := ← field j "static_private_key_hex"
    staticPub  := ← field j "static_public_key_hex"
    ephPriv    := ← field j "ephemeral_private_key_hex"
    ct         := ← field j "ciphertext_hex"
    ss         := ← field j "shared_secret_hex"
  }

def parseFile (s : String) : Except String (Array Vec) := do
  let j ← Json.parse s
  let prim ← (← j.getObjVal? "primitive").getStr?
  if prim ≠ "kem_adapter" then
    throw s!"unexpected primitive: {prim}"
  let arr ← (← j.getObjVal? "vectors").getArr?
  arr.mapM parseVec

/-- Reinterpret 32 bytes as the fixed-width vector X25519 keys use. -/
def toVec32 (b : ByteArray) : Option (Vector UInt8 32) :=
  if h : b.data.size = 32 then some ⟨b.data, h⟩ else none

def hex (v : Vector UInt8 32) : String := byteArrayToHex ⟨v.toArray⟩

/-- Run `decapM` under the named PRF. -/
def decapVec (F : Adapter.PRF) (sk ct : Vector UInt8 32) : Option (Vector UInt8 32) :=
  match decapM F X25519.Scheme ⟨sk⟩ ⟨ct⟩ (initWith (fun _ => Vector.replicate 32 0)) with
  | .ok r _    => some r
  | .error _ _ => none

/-- Run `encapM` with the recorded ephemeral as the sole seed, so the ephemeral
key it draws is the one the vector fixes. -/
def encapVec (F : Adapter.PRF) (ephSeed : Vector UInt8 32) (staticPub : Vector UInt8 32) :
    Option (Vector UInt8 32 × Vector UInt8 32) :=
  match encapM F X25519.Scheme ⟨staticPub⟩ (initWith (fun _ => ephSeed)) with
  | .ok (ct, k) _ => some (ct.data, k)
  | .error _ _    => none

def check (label : String) (want got : String) : IO Bool := do
  if want == got then
    IO.println s!"    ok   {label}"
    pure true
  else
    IO.println s!"    FAIL {label}"
    IO.println s!"           want {want}"
    IO.println s!"           got  {got}"
    pure false

/-- Returns `(ran, ok)`: whether the vector's PRF was available, and whether
every check that ran passed. -/
def runVec (v : Vec) : IO (Bool × Bool) := do
  let some sk       := toVec32 v.staticPriv | throw (IO.userError "static private key is not 32 bytes")
  let some wantPub  := toVec32 v.staticPub  | throw (IO.userError "static public key is not 32 bytes")
  let some esk      := toVec32 v.ephPriv    | throw (IO.userError "ephemeral private key is not 32 bytes")
  let some wantCt   := toVec32 v.ct         | throw (IO.userError "ciphertext is not 32 bytes")
  let some wantSS   := toVec32 v.ss         | throw (IO.userError "shared secret is not 32 bytes")

  match prfByName v.prf with
  | none =>
      IO.println s!"  {v.name}  [skipped: PRF {v.prf} not implemented here]"
      pure (false, true)
  | some F => do
      IO.println s!"  {v.name}"
      let okPub ← check "static public key" (hex wantPub) (hex (X25519.derivePub ⟨sk⟩).data
      )
      let okCt ← check "ciphertext = ephemeral public key" (hex wantCt) (hex (X25519.derivePub ⟨esk⟩).data)

      let okDecap ← match decapVec F sk wantCt with
        | none     => do IO.println "    FAIL decapsulation rejected the ciphertext"; pure false
        | some got => check "decapsulated shared secret" (hex wantSS) (hex got)

      -- The recorded ephemeral private key is already clamped, and
      -- privateKeyFromSeed clamps, which is idempotent, so feeding it as the
      -- seed reproduces exactly the vector's ephemeral.
      let okEncap ← match encapVec F esk wantPub with
        | none => do IO.println "    FAIL encapsulation rejected the public key"; pure false
        | some (gotCt, gotSS) => do
            let a ← check "encapsulated ciphertext" (hex wantCt) (hex gotCt)
            let b ← check "encapsulated shared secret" (hex wantSS) (hex gotSS)
            pure (a && b)

      pure (true, okPub && okCt && okDecap && okEncap)

def main : IO UInt32 := do
  let path := "testdata/adapter_test_vectors.json"
  let raw ← IO.FS.readFile path
  match parseFile raw with
  | .error e => do
      IO.eprintln s!"failed to parse {path}: {e}"
      pure 1
  | .ok vs => do
      IO.println s!"NIKE-to-KEM adapter vectors ({vs.size} from hpqc)"
      let mut ok := true
      let mut ran := 0
      for v in vs do
        let (didRun, vecOk) ← runVec v
        ok := ok && vecOk
        if didRun then ran := ran + 1
      IO.println ""
      if ran == 0 then
        IO.eprintln "no vector used a PRF this implementation has — nothing was verified"
        return 1
      if !ok then
        IO.eprintln s!"FAILED ({ran} of {vs.size} vectors run)"
        return 1
      IO.println s!"all checks passed ({ran} of {vs.size} vectors run; the rest name PRFs not implemented here)"
      pure 0
