/-
SPDX-FileCopyrightText: Copyright (C) 2026 David Stainton
SPDX-License-Identifier: AGPL-3.0-only
-/

import Lean.Data.Json

import CryptWalker.BACAP.API
import CryptWalker.BACAP.Impl
import CryptWalker.BACAP.Types
import CryptWalker.Util.newhex

/-! # BACAP cross-implementation test vectors

Reads JSON test vector files from `testdata/`, generated by
`hpqc/testvectors/cmd/generate`. These same files are consumed by the Go tests in
`hpqc/bacap/bacap_vectors_test.go` and the Python tests in
`py/tests/bacap/test_bacap_vectors.py`. A Lean implementation that passes all
these tests is byte-compatible with the Go implementation.

Vector files used:
- `message_box_index.json` — ratchet advance (AdvanceIndexTo)
- `box_id.json` — box ID derivation (DeriveMessageBoxID / BoxIDForContext)
- `encrypt.json` — encrypt + signature + decrypt round-trip
- `mutate_kdf_state.json` — ratchet re-seeding (MutateKDFState), the Contact Voucher primitive

The WriteCap serialization is checked against the same vectors: every `writecap_hex` is
deserialized and re-serialized, which exercises the 64-byte `seed ++ pubkey` private-key
encoding Go uses.

Two tests take no vectors and draw their keys from the system CSPRNG instead: `testGenerate`,
that a freshly generated cap can encrypt and decrypt at all, and `testAliceBob`, that a writer
and the holder of the paired read cap agree on a run of three boxes.
-/

open Lean
open CryptWalker.BACAP.Types
open CryptWalker.BACAP.Ratchet
open CryptWalker.Hash.HKDF
open CryptWalker.Sign.Ed25519Blinded
open CryptWalker.Cipher.AESGCMSIV
open CryptWalker.Util.newhex
open CryptWalker.BACAP.Impl

-- ── hex parsing ──

def hexField (j : Json) (k : String) : Except String ByteArray := do
  let s ← (← j.getObjVal? k).getStr?
  match hexStringToByteArray s with
  | some b => pure b
  | none   => throw s!"field {k}: not valid hex: {s}"

def unwrap {α : Type} : Except String α → IO α
  | .ok v    => pure v
  | .error e => throw (IO.userError e)

def parseMessageBoxIndexHex (s : String) : Option MessageBoxIndex :=
  match hexStringToByteArray s with
  | some ba =>
    if h : ba.data.size = 104 then some (unmarshalMessageBoxIndex ⟨ba.data, h⟩)
    else none
  | none => none

-- ── WriteCap deserialization ──

def parseWriteCap (data : ByteArray) : Except String WriteCap := do
  if h : data.data.size = WriteCapSize then
    pure (unmarshalWriteCap ⟨data.data, h⟩)
  else throw s!"WriteCap must be {WriteCapSize} bytes, got {data.data.size}"

-- ── helpers ──

def hexOfPubBytes (v : PubBytes) : String := byteArrayToHex ⟨v.toArray⟩
def hexOfSigBytes (s : SigBytes) : String := byteArrayToHex ⟨s.toArray⟩
def hexOfByteArray (b : ByteArray) : String := byteArrayToHex b
def vecToByteArray {n : Nat} (v : Vector UInt8 n) : ByteArray := ⟨v.toArray⟩

-- ── parse vector structures ──

structure MBIVec where
  name      : String
  initial   : ByteArray
  advanceTo : Nat
  expected  : ByteArray

def parseMBIVec (v : Json) : Except String MBIVec := do
  pure {
    name      := ← (← v.getObjVal? "name").getStr?
    initial   := ← hexField v "initial_index_hex"
    advanceTo := (← (← v.getObjVal? "advance_to").getNat?)
    expected  := ← hexField v "expected_index_hex"
  }

structure BoxIDVec where
  name       : String
  writeCapHex : ByteArray
  advanceBy  : Nat
  ctxHex     : ByteArray
  useContext : Bool
  expected   : ByteArray

def parseBoxIDVec (v : Json) : Except String BoxIDVec := do
  pure {
    name       := ← (← v.getObjVal? "name").getStr?
    writeCapHex := ← hexField v "writecap_hex"
    advanceBy  := (← (← v.getObjVal? "advance_by").getNat?)
    ctxHex     := ← hexField v "ctx_hex"
    useContext := (← (← v.getObjVal? "use_context").getBool?)
    expected   := ← hexField v "expected_box_id_hex"
  }

structure EncryptVec where
  name       : String
  writeCapHex : ByteArray
  advanceBy  : Nat
  ctxHex     : ByteArray
  plaintext  : ByteArray
  expectedBoxID      : ByteArray
  expectedCiphertext : ByteArray
  expectedSignature  : ByteArray

def parseEncryptVec (v : Json) : Except String EncryptVec := do
  pure {
    name       := ← (← v.getObjVal? "name").getStr?
    writeCapHex := ← hexField v "writecap_hex"
    advanceBy  := (← (← v.getObjVal? "advance_by").getNat?)
    ctxHex     := ← hexField v "ctx_hex"
    plaintext  := ← hexField v "plaintext_hex"
    expectedBoxID      := ← hexField v "expected_box_id_hex"
    expectedCiphertext := ← hexField v "expected_ciphertext_hex"
    expectedSignature  := ← hexField v "expected_signature_hex"
  }

structure MutateVec where
  name        : String
  writeCapHex : ByteArray
  advanceBy   : Nat
  saltHex     : ByteArray
  readCtxHex  : ByteArray
  expectedIndex : ByteArray
  expectedBoxID : ByteArray

def parseMutateVec (v : Json) : Except String MutateVec := do
  pure {
    name        := ← (← v.getObjVal? "name").getStr?
    writeCapHex := ← hexField v "writecap_hex"
    advanceBy   := (← (← v.getObjVal? "advance_by").getNat?)
    saltHex     := ← hexField v "salt_hex"
    readCtxHex  := ← hexField v "read_ctx_hex"
    expectedIndex := ← hexField v "expected_mutated_index_hex"
    expectedBoxID := ← hexField v "expected_mutated_box_id_hex"
  }

-- ── load vectors from JSON ──

def loadVectors {α} (path : String) (primName : String) (parse : Json → Except String α) : IO (Array α) := do
  let raw ← IO.FS.readFile path
  let json ← unwrap (Json.parse raw)
  let prim ← unwrap do
    let primVal ← json.getObjVal? "primitive"
    Json.getStr? primVal
  if prim ≠ primName then throw (IO.userError s!"unexpected primitive: {prim}")
  let arr ← unwrap do
    let arrVal ← json.getObjVal? "vectors"
    Json.getArr? arrVal
  arr.mapM fun v => unwrap (parse v)

-- ── tests ──

/-- The cap's index, advanced by `n` steps. `none` signals a rewind, which the vectors never ask for. -/
def advancedIndex (wc : WriteCap) (n : Nat) : Option MessageBoxIndex :=
  if n > 0 then wc.messageBoxIndex.advanceIndexTo (wc.messageBoxIndex.idx64 + n.toUInt64)
  else some wc.messageBoxIndex

def testMessageBoxIndex : IO UInt32 := do
  let vecs ← loadVectors "CryptWalker/testdata/message_box_index.json" "bacap_message_box_index" parseMBIVec
  IO.println s!"MessageBoxIndex advance ({vecs.size} vectors from hpqc)"
  let mut ok := true
  for v in vecs do
    let initialIdx ← match parseMessageBoxIndexHex (byteArrayToHex v.initial) with
      | some idx => pure idx
      | none => do IO.eprintln s!"  FAIL  {v.name}: failed to parse initial index"; ok := false; pure default
    match advanceTo initialIdx blake2b512_hkdf v.advanceTo.toUInt64 with
    | none => do IO.eprintln s!"  FAIL  {v.name}: advanceTo returned none"; ok := false
    | some result =>
      let got := vecToByteArray (marshalMessageBoxIndex result)
      if got == v.expected then
        IO.println s!"  ok    {v.name} (advance to {v.advanceTo})"
      else
        ok := false
        IO.println s!"  FAIL  {v.name}"
        IO.println s!"          want {byteArrayToHex v.expected}"
        IO.println s!"          got  {byteArrayToHex got}"
  pure (if ok then 0 else 1)

def testBoxID : IO UInt32 := do
  let vecs ← loadVectors "CryptWalker/testdata/box_id.json" "bacap_box_id" parseBoxIDVec
  IO.println s!"Box ID derivation ({vecs.size} vectors from hpqc)"
  let mut ok := true
  for v in vecs do
    let wc ← unwrap (parseWriteCap v.writeCapHex)
    let idx ← match advancedIndex wc v.advanceBy with
      | some idx => pure idx
      | none => do
        IO.eprintln s!"  FAIL  {v.name}: advanceIndexTo returned none"; ok := false
        pure wc.messageBoxIndex
    let gotBoxID :=
      if v.useContext then idx.boxIDForContext wc.readCap v.ctxHex
      else idx.deriveMessageBoxID wc.rootPublicKey
    if (vecToByteArray gotBoxID) == v.expected then
      IO.println s!"  ok    {v.name} (advance_by={v.advanceBy}, ctx={v.useContext})"
    else
      ok := false
      IO.println s!"  FAIL  {v.name}"
      IO.println s!"          want {byteArrayToHex v.expected}"
      IO.println s!"          got  {hexOfPubBytes gotBoxID}"
  pure (if ok then 0 else 1)

def testEncrypt : IO UInt32 := do
  let vecs ← loadVectors "CryptWalker/testdata/encrypt.json" "bacap_encrypt" parseEncryptVec
  IO.println s!"Encrypt ({vecs.size} vectors from hpqc)"
  let mut ok := true
  for v in vecs do
    let wc ← unwrap (parseWriteCap v.writeCapHex)
    let idx ← match advancedIndex wc v.advanceBy with
      | some idx => pure idx
      | none => do
        IO.eprintln s!"  FAIL  {v.name}: advanceIndexTo returned none"; ok := false
        pure wc.messageBoxIndex
    let (gotBoxID, gotCt, gotSig) := idx.encryptForContext wc v.ctxHex v.plaintext
    if vecToByteArray gotBoxID != v.expectedBoxID then
      ok := false
      IO.println s!"  FAIL  {v.name} box ID"
      IO.println s!"          want {byteArrayToHex v.expectedBoxID}"
      IO.println s!"          got  {hexOfPubBytes gotBoxID}"
    if gotCt != v.expectedCiphertext then
      ok := false
      IO.println s!"  FAIL  {v.name} ciphertext"
      IO.println s!"          want {byteArrayToHex v.expectedCiphertext}"
      IO.println s!"          got  {hexOfByteArray gotCt}"
    if vecToByteArray gotSig != v.expectedSignature then
      ok := false
      IO.println s!"  FAIL  {v.name} signature"
      IO.println s!"          want {byteArrayToHex v.expectedSignature}"
      IO.println s!"          got  {hexOfSigBytes gotSig}"
    match idx.decryptForContext gotBoxID v.ctxHex gotCt gotSig with
    | some recovered =>
      if recovered == v.plaintext then
        IO.println s!"  ok    {v.name} (encrypt + decrypt round-trip)"
      else
        ok := false
        IO.println s!"  FAIL  {v.name} decrypt round-trip"
        IO.println s!"          want {byteArrayToHex v.plaintext}"
        IO.println s!"          got  {hexOfByteArray recovered}"
    | none =>
      ok := false
      IO.println s!"  FAIL  {v.name} decrypt returned none"
  pure (if ok then 0 else 1)

def testWriteCapRoundTrip : IO UInt32 := do
  let vecs ← loadVectors "CryptWalker/testdata/box_id.json" "bacap_box_id" parseBoxIDVec
  IO.println s!"WriteCap serialization ({vecs.size} write caps from hpqc)"
  let mut ok := true
  for v in vecs do
    let wc ← unwrap (parseWriteCap v.writeCapHex)
    let got := vecToByteArray (marshalWriteCap wc)
    if got == v.writeCapHex then
      IO.println s!"  ok    {v.name} (unmarshal + marshal round-trip)"
    else
      ok := false
      IO.println s!"  FAIL  {v.name}"
      IO.println s!"          want {byteArrayToHex v.writeCapHex}"
      IO.println s!"          got  {byteArrayToHex got}"
  pure (if ok then 0 else 1)

def testMutateKDFState : IO UInt32 := do
  let vecs ← loadVectors "CryptWalker/testdata/mutate_kdf_state.json" "bacap_mutate_kdf_state"
    parseMutateVec
  IO.println s!"MutateKDFState ({vecs.size} vectors from hpqc)"
  let mut ok := true
  for v in vecs do
    let mut vecOk := true
    let wc ← unwrap (parseWriteCap v.writeCapHex)
    let idx ← match advancedIndex wc v.advanceBy with
      | some idx => pure idx
      | none => do
        IO.eprintln s!"  FAIL  {v.name}: advanceIndexTo returned none"; vecOk := false
        pure wc.messageBoxIndex
    let mutated := idx.mutateKDFState v.saltHex
    let gotIndex := vecToByteArray (marshalMessageBoxIndex mutated)
    if gotIndex != v.expectedIndex then
      vecOk := false
      IO.println s!"  FAIL  {v.name} mutated index"
      IO.println s!"          want {byteArrayToHex v.expectedIndex}"
      IO.println s!"          got  {byteArrayToHex gotIndex}"
    let gotBoxID := vecToByteArray (mutated.boxIDForContext wc.readCap v.readCtxHex)
    if gotBoxID != v.expectedBoxID then
      vecOk := false
      IO.println s!"  FAIL  {v.name} mutated box ID"
      IO.println s!"          want {byteArrayToHex v.expectedBoxID}"
      IO.println s!"          got  {byteArrayToHex gotBoxID}"
    if vecOk then IO.println s!"  ok    {v.name} (advance_by={v.advanceBy})"
    else ok := false
  pure (if ok then 0 else 1)

/-- Smoke test for the `IO` constructors: a freshly generated cap must actually work.
    There are no vectors for this one, the key material is random by construction. -/
def testGenerate : IO UInt32 := do
  IO.println "Key generation (system CSPRNG)"
  let wc ← WriteCap.generate
  let idx := wc.messageBoxIndex
  let ctx := "lean keygen smoke test".toUTF8
  let plaintext := "attack at dawn".toUTF8
  let (boxID, ct, sig) := idx.encryptForContext wc ctx plaintext
  let mut ok := true
  if !verifyBox boxID ct sig then
    ok := false
    IO.println "  FAIL  signature does not verify under the derived box ID"
  if vecToByteArray (idx.boxIDForContext wc.readCap ctx) != vecToByteArray boxID then
    ok := false
    IO.println "  FAIL  read cap derives a different box ID than the write cap encrypted under"
  match idx.decryptForContext boxID ctx ct sig with
  | some recovered =>
    if recovered != plaintext then
      ok := false
      IO.println "  FAIL  decrypt round-trip returned the wrong plaintext"
  | none =>
    ok := false
    IO.println "  FAIL  decrypt returned none"
  if ok then
    IO.println s!"  ok    fresh cap encrypts, verifies and decrypts (start index {idx.idx64})"
  pure (if ok then 0 else 1)

/-- The next `n` indices of a ratchet, starting at `start` itself. -/
def indexRun : MessageBoxIndex → Nat → Option (Array MessageBoxIndex)
  | _,     0     => some #[]
  | start, n + 1 => do pure (#[start] ++ (← indexRun (← start.nextIndex) n))

/-- Alice writes three boxes, Bob reads them.

Alice holds the write cap and never parts with it. Bob gets the paired read cap and nothing
else: no seed, no private key, and not even the box IDs. He walks his own copy of the ratchet
to derive the same three box IDs, which is how a reader locates boxes in the first place, and
the same three AEAD keys, which is how he opens them. -/
def testAliceBob : IO UInt32 := do
  IO.println "Alice and Bob (system CSPRNG)"
  let mut ok := true

  let alice ← WriteCap.generate
  let bob := alice.readCap
  let ctx := "alice and bob, chapter one".toUTF8
  let messages := #["meet me at the old bridge",
                    "bring the umbrella",
                    "the crow flies at midnight"]

  let some aliceIdx := indexRun alice.messageBoxIndex messages.size
    | do IO.println "  FAIL  Alice could not advance her ratchet"; return 1
  let mut boxes := #[]
  for (idx, msg) in aliceIdx.zip messages do
    boxes := boxes.push (idx.encryptForContext alice ctx msg.toUTF8)

  let ids := (boxes.map fun b => hexOfPubBytes b.1).toList
  if ids.eraseDups.length != ids.length then
    ok := false
    IO.println "  FAIL  Alice reused a box ID across the three writes"
  else
    IO.println s!"  ok    Alice wrote {boxes.size} boxes to distinct IDs"

  let some bobIdx := indexRun bob.messageBoxIndex boxes.size
    | do IO.println "  FAIL  Bob could not advance his ratchet"; return 1

  for i in [0:boxes.size] do
    let (boxID, ct, sig) := boxes[i]!
    let idx := bobIdx[i]!
    let label := s!"box {i + 1}"
    if hexOfPubBytes (idx.boxIDForContext bob ctx) != hexOfPubBytes boxID then
      ok := false
      IO.println s!"  FAIL  {label}: Bob derived a different box ID than Alice wrote to"
    else if !verifyBox boxID ct sig then
      ok := false
      IO.println s!"  FAIL  {label}: signature does not verify under the box ID"
    else
      match idx.decryptForContext boxID ctx ct sig with
      | some recovered =>
        if recovered != messages[i]!.toUTF8 then
          ok := false
          IO.println s!"  FAIL  {label}: decrypted to the wrong plaintext"
        else
          IO.println s!"  ok    {label}  \"{messages[i]!}\""
      | none =>
        ok := false
        IO.println s!"  FAIL  {label}: decrypt returned none"

  let (boxID₂, ct₂, sig₂) := boxes[1]!
  match bobIdx[0]!.decryptForContext boxID₂ ctx ct₂ sig₂ with
  | none   => IO.println "  ok    the key for one box does not open the next"
  | some _ =>
    ok := false
    IO.println "  FAIL  the first box's key opened the second box"

  pure (if ok then 0 else 1)

def main : IO UInt32 := do
  let r1 ← testMessageBoxIndex
  IO.println ""
  let r2 ← testBoxID
  IO.println ""
  let r3 ← testEncrypt
  IO.println ""
  let r4 ← testWriteCapRoundTrip
  IO.println ""
  let r5 ← testMutateKDFState
  IO.println ""
  let r6 ← testGenerate
  IO.println ""
  let r7 ← testAliceBob
  IO.println ""
  if r1 == 0 && r2 == 0 && r3 == 0 && r4 == 0 && r5 == 0 && r6 == 0 && r7 == 0 then
    IO.println "all BACAP vectors passed"
    pure 0
  else
    IO.eprintln "some BACAP vectors FAILED"
    pure 1
